set MMDPS_ROOTDIR=E:/MMDPSoftware/mmdps
set MMDPS_BUILTINPATH=%MMDPS_ROOTDIR%/pipeline;%MMDPS_ROOTDIR%/pipeline/T1;%MMDPS_ROOTDIR%/pipeline/BOLD;%MMDPS_ROOTDIR%/pipeline/DWI;%MMDPS_ROOTDIR%/mmdps/proc
