spmjobfiles_T1 = {'sample_spm_GunZip_T1.m', 'sample_spm_Segment_T1.m',...
    'sample_spm_imCalc_T1_brain.m', 'sample_spm_Normalize_wri.m',...
    'sample_spm_imCalc_iwT1_brain.m'};

run_spm_jobs(spmjobfiles_T1);
